/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PriceFeedAdapterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "STALE_THRESHOLD"
      | "feeds"
      | "getLatestPrice"
      | "getPrice"
      | "setFeed"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "FeedSet"): EventFragment;

  encodeFunctionData(
    functionFragment: "STALE_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "feeds", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getLatestPrice",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "getPrice", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setFeed",
    values: [string, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "STALE_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feeds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLatestPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setFeed", data: BytesLike): Result;
}

export namespace FeedSetEvent {
  export type InputTuple = [asset: string, aggregator: AddressLike];
  export type OutputTuple = [asset: string, aggregator: string];
  export interface OutputObject {
    asset: string;
    aggregator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PriceFeedAdapter extends BaseContract {
  connect(runner?: ContractRunner | null): PriceFeedAdapter;
  waitForDeployment(): Promise<this>;

  interface: PriceFeedAdapterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  STALE_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  feeds: TypedContractMethod<[arg0: string], [string], "view">;

  getLatestPrice: TypedContractMethod<
    [asset: string],
    [[bigint, bigint] & { price: bigint; updatedAt: bigint }],
    "view"
  >;

  getPrice: TypedContractMethod<[asset: string], [bigint], "view">;

  setFeed: TypedContractMethod<
    [asset: string, feed: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "STALE_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "feeds"
  ): TypedContractMethod<[arg0: string], [string], "view">;
  getFunction(
    nameOrSignature: "getLatestPrice"
  ): TypedContractMethod<
    [asset: string],
    [[bigint, bigint] & { price: bigint; updatedAt: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPrice"
  ): TypedContractMethod<[asset: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "setFeed"
  ): TypedContractMethod<
    [asset: string, feed: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "FeedSet"
  ): TypedContractEvent<
    FeedSetEvent.InputTuple,
    FeedSetEvent.OutputTuple,
    FeedSetEvent.OutputObject
  >;

  filters: {
    "FeedSet(string,address)": TypedContractEvent<
      FeedSetEvent.InputTuple,
      FeedSetEvent.OutputTuple,
      FeedSetEvent.OutputObject
    >;
    FeedSet: TypedContractEvent<
      FeedSetEvent.InputTuple,
      FeedSetEvent.OutputTuple,
      FeedSetEvent.OutputObject
    >;
  };
}
