/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface TapOrderInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DURATION_15M"
      | "DURATION_1M"
      | "DURATION_5M"
      | "addAsset"
      | "allowedMultipliers"
      | "assetFeeds"
      | "batchSettle"
      | "createOrder"
      | "nextOrderId"
      | "orders"
      | "owner"
      | "pause"
      | "paused"
      | "payoutPool"
      | "priceFeedAdapter"
      | "renounceOwnership"
      | "settleOrder"
      | "settled"
      | "transferOwnership"
      | "unpause"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AssetAdded"
      | "OrderCreated"
      | "OrderLost"
      | "OrderWon"
      | "OwnershipTransferred"
      | "Paused"
      | "PausedToggled"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DURATION_15M",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DURATION_1M",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DURATION_5M",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addAsset",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "allowedMultipliers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "assetFeeds", values: [string]): string;
  encodeFunctionData(
    functionFragment: "batchSettle",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "createOrder",
    values: [string, BigNumberish, boolean, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextOrderId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "orders",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payoutPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "priceFeedAdapter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "settleOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "settled",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "DURATION_15M",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DURATION_1M",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DURATION_5M",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addAsset", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "allowedMultipliers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "assetFeeds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "batchSettle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextOrderId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "orders", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payoutPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "priceFeedAdapter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "settled", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
}

export namespace AssetAddedEvent {
  export type InputTuple = [assetKey: string, feed: AddressLike];
  export type OutputTuple = [assetKey: string, feed: string];
  export interface OutputObject {
    assetKey: string;
    feed: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderCreatedEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    user: AddressLike,
    assetKey: string,
    targetPrice: BigNumberish,
    isAbove: boolean,
    stake: BigNumberish,
    multiplierBps: BigNumberish,
    expiry: BigNumberish
  ];
  export type OutputTuple = [
    orderId: bigint,
    user: string,
    assetKey: string,
    targetPrice: bigint,
    isAbove: boolean,
    stake: bigint,
    multiplierBps: bigint,
    expiry: bigint
  ];
  export interface OutputObject {
    orderId: bigint;
    user: string;
    assetKey: string;
    targetPrice: bigint;
    isAbove: boolean;
    stake: bigint;
    multiplierBps: bigint;
    expiry: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderLostEvent {
  export type InputTuple = [orderId: BigNumberish, user: AddressLike];
  export type OutputTuple = [orderId: bigint, user: string];
  export interface OutputObject {
    orderId: bigint;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderWonEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    user: AddressLike,
    payout: BigNumberish
  ];
  export type OutputTuple = [orderId: bigint, user: string, payout: bigint];
  export interface OutputObject {
    orderId: bigint;
    user: string;
    payout: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedToggledEvent {
  export type InputTuple = [isPaused: boolean];
  export type OutputTuple = [isPaused: boolean];
  export interface OutputObject {
    isPaused: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TapOrder extends BaseContract {
  connect(runner?: ContractRunner | null): TapOrder;
  waitForDeployment(): Promise<this>;

  interface: TapOrderInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DURATION_15M: TypedContractMethod<[], [bigint], "view">;

  DURATION_1M: TypedContractMethod<[], [bigint], "view">;

  DURATION_5M: TypedContractMethod<[], [bigint], "view">;

  addAsset: TypedContractMethod<
    [assetKey: string, feed: AddressLike],
    [void],
    "nonpayable"
  >;

  allowedMultipliers: TypedContractMethod<
    [arg0: BigNumberish],
    [boolean],
    "view"
  >;

  assetFeeds: TypedContractMethod<[arg0: string], [string], "view">;

  batchSettle: TypedContractMethod<
    [orderIds: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  createOrder: TypedContractMethod<
    [
      assetKey: string,
      targetPrice: BigNumberish,
      isAbove: boolean,
      durationSecs: BigNumberish,
      multiplierBps: BigNumberish
    ],
    [void],
    "payable"
  >;

  nextOrderId: TypedContractMethod<[], [bigint], "view">;

  orders: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, boolean, bigint, bigint, bigint, bigint] & {
        user: string;
        assetKey: string;
        targetPrice: bigint;
        isAbove: boolean;
        stake: bigint;
        multiplierBps: bigint;
        expiry: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  payoutPool: TypedContractMethod<[], [string], "view">;

  priceFeedAdapter: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  settleOrder: TypedContractMethod<
    [orderId: BigNumberish],
    [void],
    "nonpayable"
  >;

  settled: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DURATION_15M"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DURATION_1M"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DURATION_5M"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addAsset"
  ): TypedContractMethod<
    [assetKey: string, feed: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "allowedMultipliers"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "assetFeeds"
  ): TypedContractMethod<[arg0: string], [string], "view">;
  getFunction(
    nameOrSignature: "batchSettle"
  ): TypedContractMethod<[orderIds: BigNumberish[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createOrder"
  ): TypedContractMethod<
    [
      assetKey: string,
      targetPrice: BigNumberish,
      isAbove: boolean,
      durationSecs: BigNumberish,
      multiplierBps: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "nextOrderId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "orders"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, boolean, bigint, bigint, bigint, bigint] & {
        user: string;
        assetKey: string;
        targetPrice: bigint;
        isAbove: boolean;
        stake: bigint;
        multiplierBps: bigint;
        expiry: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "payoutPool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "priceFeedAdapter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settleOrder"
  ): TypedContractMethod<[orderId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settled"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "AssetAdded"
  ): TypedContractEvent<
    AssetAddedEvent.InputTuple,
    AssetAddedEvent.OutputTuple,
    AssetAddedEvent.OutputObject
  >;
  getEvent(
    key: "OrderCreated"
  ): TypedContractEvent<
    OrderCreatedEvent.InputTuple,
    OrderCreatedEvent.OutputTuple,
    OrderCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OrderLost"
  ): TypedContractEvent<
    OrderLostEvent.InputTuple,
    OrderLostEvent.OutputTuple,
    OrderLostEvent.OutputObject
  >;
  getEvent(
    key: "OrderWon"
  ): TypedContractEvent<
    OrderWonEvent.InputTuple,
    OrderWonEvent.OutputTuple,
    OrderWonEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PausedToggled"
  ): TypedContractEvent<
    PausedToggledEvent.InputTuple,
    PausedToggledEvent.OutputTuple,
    PausedToggledEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "AssetAdded(string,address)": TypedContractEvent<
      AssetAddedEvent.InputTuple,
      AssetAddedEvent.OutputTuple,
      AssetAddedEvent.OutputObject
    >;
    AssetAdded: TypedContractEvent<
      AssetAddedEvent.InputTuple,
      AssetAddedEvent.OutputTuple,
      AssetAddedEvent.OutputObject
    >;

    "OrderCreated(uint256,address,string,int256,bool,uint256,uint256,uint256)": TypedContractEvent<
      OrderCreatedEvent.InputTuple,
      OrderCreatedEvent.OutputTuple,
      OrderCreatedEvent.OutputObject
    >;
    OrderCreated: TypedContractEvent<
      OrderCreatedEvent.InputTuple,
      OrderCreatedEvent.OutputTuple,
      OrderCreatedEvent.OutputObject
    >;

    "OrderLost(uint256,address)": TypedContractEvent<
      OrderLostEvent.InputTuple,
      OrderLostEvent.OutputTuple,
      OrderLostEvent.OutputObject
    >;
    OrderLost: TypedContractEvent<
      OrderLostEvent.InputTuple,
      OrderLostEvent.OutputTuple,
      OrderLostEvent.OutputObject
    >;

    "OrderWon(uint256,address,uint256)": TypedContractEvent<
      OrderWonEvent.InputTuple,
      OrderWonEvent.OutputTuple,
      OrderWonEvent.OutputObject
    >;
    OrderWon: TypedContractEvent<
      OrderWonEvent.InputTuple,
      OrderWonEvent.OutputTuple,
      OrderWonEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PausedToggled(bool)": TypedContractEvent<
      PausedToggledEvent.InputTuple,
      PausedToggledEvent.OutputTuple,
      PausedToggledEvent.OutputObject
    >;
    PausedToggled: TypedContractEvent<
      PausedToggledEvent.InputTuple,
      PausedToggledEvent.OutputTuple,
      PausedToggledEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
